# Generated by Django 3.1.2 on 2020-12-24 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201224_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advuser',
            old_name='is_actived',
            new_name='is_activated',
        ),
    ]
